; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = yolo_uno_sensor

[env:base]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -DSSID_AP='"ESP32 LOCAL"'
    -DPASS_AP='12345678'
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1


lib_deps = 
    # The exact version
    #robtillaart/DHT20 @ 0.3.1
    tanakamasayuki/TensorFlowLite_ESP32@1.0.0
    adafruit/Adafruit NeoPixel@^1.15.1
    DHT20
    LCD
    PubSubClient
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    ThingsBoard
    ArduinoJson
    LittleFS
    AsyncTCP
    ElegantOTA

lib_compat_mode = strict

[env:yolo_uno_sensor]
extends = env:base
upload_port = COM9
monitor_port = COM9
build_flags =
    ${env:base.build_flags}
    -DSSID_AP='"ESP32 SENSOR"'
    -DDEVICE_ROLE_SENSOR=1

[env:yolo_uno_actuator]
extends = env:base
upload_port = COM4
monitor_port = COM4
build_flags =
    ${env:base.build_flags}
    -DSSID_AP='"ESP32 ACTUATOR"'
    -DDEVICE_ROLE_ACTUATOR=1
    -DDEVICE_WIFI_SSID='"Pi"'
    -DDEVICE_WIFI_PASS='"123456789"'
    -DDEVICE_CORE_IOT_TOKEN='"d31qkVPHrtOZVVhdXkdg"'